#!/usr/bin/env bash
#
# Onboards a NEW vendor/channel: generates a shared HMAC secret and writes a
# .env.<vendor>.<channel> config file, ready to be dropped into CONFIG_DIR
# (see docker-compose.yml's app volume mount and internal/infrastructure/
# config/vendor_config.go's VendorConfigLoader).
#
# Unlike merchant onboarding, this involves NO API call and NO RSA keypair —
# vendor-facing endpoints (inquiry/payment/status) are verified with a
# symmetric HMAC secret only (feature 009-transfer-va-auth), sourced purely
# from this config file. The server picks it up automatically (or after a
# restart) the moment the file exists under CONFIG_DIR — no admin
# registration step exists or is needed for vendors.
#
# Usage:
#   ./scripts/onboard-vendor.sh -n <vendor> -c <channel> [-i <client-id>] [-o <output-dir>]
#
# After running, hand the generated VENDOR_CLIENT_SECRET value to the vendor
# through a secure out-of-band channel — it is never transmitted or
# registered via any API in this system.
#
# Requires: openssl, uuidgen
set -euo pipefail

OUTPUT_DIR="."
VENDOR=""
CHANNEL=""
CLIENT_ID=""

usage() {
	echo "Usage: $0 -n <vendor> -c <channel> [-i <client-id>] [-o <output-dir>]" >&2
	exit 1
}

while getopts "n:c:i:o:h" opt; do
	case "$opt" in
	n) VENDOR="$OPTARG" ;;
	c) CHANNEL="$OPTARG" ;;
	i) CLIENT_ID="$OPTARG" ;;
	o) OUTPUT_DIR="$OPTARG" ;;
	h | *) usage ;;
	esac
done

[[ -z "$VENDOR" || -z "$CHANNEL" ]] && usage
[[ -z "$CLIENT_ID" ]] && CLIENT_ID="$(uuidgen)"

ENV_FILE="${OUTPUT_DIR}/.env.${VENDOR}.${CHANNEL}"
if [[ -f "$ENV_FILE" ]]; then
	echo "!! ${ENV_FILE} already exists — refusing to overwrite. Remove it first if you really want to regenerate." >&2
	exit 1
fi

SECRET="$(openssl rand -hex 32)"

cat > "$ENV_FILE" <<EOF
# Vendor channel configuration for '${VENDOR}/${CHANNEL}' — generated by
# onboard-vendor.sh. This IS read by the server (VendorConfigLoader), unlike
# .env.merchant.* files. Copy/mount it under CONFIG_DIR before starting the
# app, or restart the app after adding it.
#
# NEVER commit this file — it contains a live shared secret.
VENDOR_CLIENT_ID=${CLIENT_ID}
VENDOR_CLIENT_SECRET=${SECRET}

# ============================================================
# Base URL (only relevant if this service also calls OUT to the vendor's
# own API as a client — internal/adapter/gateway/snap/client.go). Leave the
# defaults if this vendor only calls INTO this service.
# ============================================================
VENDOR_BASE_URL=https://sandbox.${VENDOR}.co.id
VENDOR_TOKEN_ENDPOINT=/openapi/v1.0/access-token/b2b
VENDOR_ENDPOINT_INQUIRY=/openapi/v1.0/transfer-va/inquiry
VENDOR_ENDPOINT_STATUS=/openapi/v1.0/transfer-va/status
VENDOR_ENDPOINT_PAYMENT=/openapi/v1.0/transfer-va/payment

# ============================================================
# Channel Configuration — fill in per the vendor's actual assigned values
# ============================================================
VENDOR_CHANNEL_ID=
VENDOR_PARTNER_ID=
VENDOR_ORIGIN=yourdomain.com

# ============================================================
# SNAP Headers required on inbound requests from this vendor. Per ASPI spec,
# transfer-va endpoints require X-TIMESTAMP, X-SIGNATURE, X-PARTNER-ID,
# X-EXTERNAL-ID. Do NOT add X-CLIENT-KEY here — it is only used on the
# access-token endpoint, never on transfer-va endpoints.
# ============================================================
VENDOR_REQUIRED_HEADERS=X-TIMESTAMP,X-SIGNATURE,X-PARTNER-ID,X-EXTERNAL-ID

VENDOR_SIGNATURE_ALGORITHM=HMAC-SHA512
VENDOR_RESPONSE_CODE_FORMAT=AAABBCC
EOF
chmod 600 "$ENV_FILE"

echo "=================================================================="
echo "Done. Vendor '${VENDOR}/${CHANNEL}' config written to ${ENV_FILE} (mode 600)."
echo "  clientId (informational only, not verified anywhere): ${CLIENT_ID}"
echo "  VENDOR_CLIENT_SECRET: ${SECRET}"
echo
echo "Next steps:"
echo "  1. Fill in VENDOR_CHANNEL_ID / VENDOR_PARTNER_ID with the vendor's assigned values."
echo "  2. Share VENDOR_CLIENT_SECRET with the vendor over a secure channel."
echo "  3. Mount/copy ${ENV_FILE} into CONFIG_DIR and restart the app."
echo "=================================================================="
