#!/usr/bin/env bash
#
# Onboards a NEW merchant end-to-end: generates its RSA keypair (for B2B
# accessToken issuance) and its HMAC shared secret (feature
# 010-merchant-hmac-signature), registers both against a running instance's
# admin API, and writes a local .env.merchant.<name> credentials file that
# other scripts (merchant-create-va.sh, merchant-list-va.sh,
# merchant-delete-va.sh, curl-b2b-token.sh) can load via -f.
#
# This credentials file is a LOCAL TEST-TOOLING convenience only — the
# server itself never reads it. The server's only source of truth for a
# merchant's identity/keys/secret is the client_apps/client_keys/
# client_secrets database tables, populated here via the admin API.
#
# Usage:
#   ./scripts/onboard-merchant.sh -n <merchant-name> [-i <client-id>] [-K <admin-api-key>] [-u <base-url>] [-o <output-dir>]
#
# -n <merchant-name> becomes the credentials filename: .env.merchant.<name>
#    (and the default client_name if -i's clientId isn't already registered).
# -i <client-id> lets you reuse an existing clientId (e.g. one already known
#    to some external system); defaults to a fresh UUID.
# -K <admin-api-key> is required — this hits admin-only endpoints.
# -o <output-dir> defaults to the repo root; keypair files are written as
#    <output-dir>/merchant-<name>-private.pem / -public.pem.
#
# Requires: curl, openssl, jq, uuidgen
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

BASE_URL="http://localhost:8080"
MERCHANT_NAME=""
CLIENT_ID=""
ADMIN_API_KEY=""
OUTPUT_DIR="$REPO_ROOT"

usage() {
	echo "Usage: $0 -n <merchant-name> [-i <client-id>] -K <admin-api-key> [-u <base-url>] [-o <output-dir>]" >&2
	exit 1
}

while getopts "n:i:K:u:o:h" opt; do
	case "$opt" in
	n) MERCHANT_NAME="$OPTARG" ;;
	i) CLIENT_ID="$OPTARG" ;;
	K) ADMIN_API_KEY="$OPTARG" ;;
	u) BASE_URL="$OPTARG" ;;
	o) OUTPUT_DIR="$OPTARG" ;;
	h | *) usage ;;
	esac
done

[[ -z "$MERCHANT_NAME" || -z "$ADMIN_API_KEY" ]] && usage
command -v jq >/dev/null || { echo "jq is required" >&2; exit 1; }

[[ -z "$CLIENT_ID" ]] && CLIENT_ID="$(uuidgen)"

PRIVATE_KEY_PATH="${OUTPUT_DIR}/merchant-${MERCHANT_NAME}-private.pem"
PUBLIC_KEY_PATH="${OUTPUT_DIR}/merchant-${MERCHANT_NAME}-public.pem"
ENV_FILE="${REPO_ROOT}/.env.merchant.${MERCHANT_NAME}"

echo "=================================================================="
echo "Step 1: Generate RSA keypair for merchant '${MERCHANT_NAME}'"
echo "=================================================================="
openssl genpkey -algorithm RSA -out "$PRIVATE_KEY_PATH" -pkeyopt rsa_keygen_bits:2048 2>/dev/null
openssl rsa -in "$PRIVATE_KEY_PATH" -pubout -out "$PUBLIC_KEY_PATH" 2>/dev/null
chmod 600 "$PRIVATE_KEY_PATH"
echo "==> Private key: ${PRIVATE_KEY_PATH} (mode 600 — keep secret, never commit)"
echo "==> Public key:  ${PUBLIC_KEY_PATH}"
echo

echo "=================================================================="
echo "Step 2: Register client_app + client_key (POST /admin/clients)"
echo "=================================================================="
PUBLIC_KEY_PEM="$(cat "$PUBLIC_KEY_PATH")"
REGISTER_BODY="$(jq -n \
	--arg clientId "$CLIENT_ID" \
	--arg clientName "$MERCHANT_NAME" \
	--arg keyId "key-01" \
	--arg publicKeyPem "$PUBLIC_KEY_PEM" \
	'{clientId: $clientId, clientName: $clientName, keyId: $keyId, publicKeyPem: $publicKeyPem}')"

REGISTER_RESP="$(curl -sS -X POST "${BASE_URL}/admin/clients" \
	-H "X-Admin-API-Key: ${ADMIN_API_KEY}" \
	-H "Content-Type: application/json" \
	-d "$REGISTER_BODY")"
echo "$REGISTER_RESP" | jq .
if [[ "$(echo "$REGISTER_RESP" | jq -r '.status // empty')" != "ok" ]]; then
	echo "!! Client registration failed — aborting." >&2
	exit 1
fi
echo "==> clientId: ${CLIENT_ID}"
echo

echo "=================================================================="
echo "Step 3: Provision HMAC shared secret (POST /admin/clients/:clientId/secret)"
echo "=================================================================="
SECRET_ID="secret-01"
SECRET_VALUE="$(openssl rand -hex 32)"
SECRET_BODY="$(jq -n --arg secretId "$SECRET_ID" --arg secretValue "$SECRET_VALUE" '{secretId: $secretId, secretValue: $secretValue}')"

SECRET_RESP="$(curl -sS -X POST "${BASE_URL}/admin/clients/${CLIENT_ID}/secret" \
	-H "X-Admin-API-Key: ${ADMIN_API_KEY}" \
	-H "Content-Type: application/json" \
	-d "$SECRET_BODY")"
echo "$SECRET_RESP" | jq .
if [[ "$(echo "$SECRET_RESP" | jq -r '.status // empty')" != "ok" ]]; then
	echo "!! Secret provisioning failed — aborting." >&2
	exit 1
fi
echo

echo "=================================================================="
echo "Step 4: Write credentials file"
echo "=================================================================="
cat > "$ENV_FILE" <<EOF
# Merchant test credentials for '${MERCHANT_NAME}' — generated by onboard-merchant.sh.
# LOCAL TEST TOOLING ONLY: the server never reads this file. It is a
# convenience for scripts/merchant-*.sh, scripts/curl-b2b-token.sh
# (via their -f flag) to load these values without retyping them.
# NEVER commit this file — it contains a live shared secret.
MERCHANT_CLIENT_ID=${CLIENT_ID}
MERCHANT_PRIVATE_KEY_PATH=${PRIVATE_KEY_PATH}
MERCHANT_PUBLIC_KEY_PATH=${PUBLIC_KEY_PATH}
MERCHANT_SECRET_ID=${SECRET_ID}
MERCHANT_SECRET_VALUE=${SECRET_VALUE}
EOF
chmod 600 "$ENV_FILE"
echo "==> Wrote ${ENV_FILE} (mode 600)"
echo
echo "=================================================================="
echo "Done. Merchant '${MERCHANT_NAME}' onboarded."
echo "  clientId: ${CLIENT_ID}"
echo "  Use -f ${ENV_FILE} with merchant-create-va.sh / merchant-list-va.sh / merchant-delete-va.sh"
echo "=================================================================="
